### ISSUE TITLE
Provide branding and link to Github - so we know it is yours?

### ISSUE THREAD

**Issue by stefek99** [ConsenSys/Token-Factory#53]
Friend recommended: http://tokenfactory.surge.sh/#/

No idea where to find the source.

Google "token factory" and this is the first result...

_(no idea though)_

___________

> Token Factory, an application that lets you create these tokens, just to play around with: https://tokenfactory.surge.sh

https://theethereum.wiki/w/index.php/ERC20_Token_Standard

**Comment by piotrkochan** [comment]
You can use https://openzeppelin.org/

**Comment by stefek99** [comment]
Unrelated.
